name: CI for Collision Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./project/requirements.txt

      # Step 4: Run tests from tests.sh
      - name: Run tests from tests.sh
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh  # Ensure tests.sh is in the right directory

      # Step 5: Upload feedback (optional, if your tests generate feedback)
      - name: Upload feedback
        uses: actions/upload-artifact@v4
        with:
          name: all-test-feedback
          path: ./project/feedback.txt
